import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type ActiveModel = {
  id: string;
  name: string;
  version: string;
  horizon: number;
  is_active: boolean;
  created_at: string;
};

type Prediction = {
  id: string;
  target_date: string;
  predicted_demand_kwh: number;
  actual_demand_kwh: number | null;
  model_id: string;
  model_name?: string;
  model_version?: string;
  horizon?: number;
  created_at: string;
};

type Demand = { date: string; demand_kwh: number };
type ListResponse<T> = { items: T[]; total: number };

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "http://127.0.0.1:8000";
const DATE_RANGE = { min: "2000-01-02", max: "2023-12-31", discontinuity: "2015-12-31" };

type Language = "en" | "es";

const translations = {
  en: {
    languageLabel: "Language selector",
    statusChecking: "Checking backend",
    statusOnline: "Backend online",
    statusOffline: "Backend offline",
    heroEyebrow: "H+1 forecast workspace",
    heroTitle: "Explore next-day demand predictions across the available historical dataset and compare them with actual demand.",
    heroLead:
      "This console presents the model developed to forecast next-day energy demand using the available historical data. Predictions use only information available before each target date and can be compared with historical actual values.",
    activeModel: "Active model",
    unavailable: "Unavailable",
    newPrediction: "New prediction",
    chooseDate: "Choose a target date",
    targetDate: "Target date",
    hPlusOne: "H+1",
    availableFrom: "Available from",
    to: "to",
    selectorReady: "Ready for a valid H+1 request.",
    invalidDate: "Invalid date selected.",
    dateBeforeStart: "The earliest valid target date is 02/01/2000.",
    dateAfterEnd: "The historical dataset ends on 31/12/2023.",
    referenceMissing:
      "The reference day is unavailable because the historical demand has a real discontinuity on 31/12/2015. This also affects 01/01/2016.",
    runForecast: "Run forecast",
    calculating: "Calculating...",
    latestResult: "Latest result",
    storedPredictions: "Stored predictions",
    forecastLedger: "Forecast ledger",
    noStoredPredictions: "No stored predictions yet.",
    predictionVsActual: "Prediction vs Actual",
    historicalComparison: "Historical comparison",
    date: "Date",
    predicted: "Predicted",
    actual: "Actual",
    absError: "Abs error",
    matchWithActual: "Match with actual value",
    model: "Model",
    notAvailable: "Not available",
    historicalDemand: "Historical demand",
    recentDailyObservations: "Recent daily observations",
    noDemandRecords: "No demand records.",
    selectorTooltip:
      "Target date for the H+1 forecast. It must be within the available historical range, and the reference day before it must exist in the dataset.",
    predictionsTooltip:
      "Predictions generated by the API and stored in PostgreSQL/Supabase for the selected model and historical dates.",
    activeModelTooltip:
      "Model developed and evaluated in this project for H+1 energy demand forecasting. The active version corresponds to the model selected after comparing alternatives through temporal evaluation on historical data.",
    comparisonTooltip:
      "Predicted demand, actual demand, absolute error and relative error for the stored prediction records.",
    historicalTooltip:
      "Historical daily demand used as the reference base for the H+1 forecast and model comparison.",
    backendUnavailable: "Backend unavailable",
    predictionUnavailable: "Prediction unavailable",
    recordCount: "stored records",
    recordLabel: "records",
    languageToggle: "Language",
    dataSource: "Data source: XM Colombia — historical energy demand data from the National Interconnected System (SIN).",
  },
  es: {
    languageLabel: "Selector de idioma",
    statusChecking: "Comprobando backend",
    statusOnline: "Backend disponible",
    statusOffline: "Backend no disponible",
    heroEyebrow: "Espacio de pronóstico H+1",
    heroTitle: "Explora pronósticos de demanda energética en el margen del historial disponible y compáralos con la demanda real.",
    heroLead:
      "Las predicciones utilizan únicamente información disponible antes de cada fecha objetivo y se comparan con los valores reales históricos registrados en el conjunto de datos.",
    activeModel: "Modelo activo",
    unavailable: "No disponible",
    newPrediction: "Nueva predicción",
    chooseDate: "Elige una fecha para predecir",
    targetDate: "Fecha objetivo",
    hPlusOne: "H+1",
    availableFrom: "Disponible desde",
    to: "hasta",
    selectorReady: "Listo para una solicitud H+1 válida.",
    invalidDate: "La fecha seleccionada no es válida.",
    dateBeforeStart: "La fecha objetivo más temprana válida es 02/01/2000.",
    dateAfterEnd: "El historial disponible termina el 31/12/2023.",
    referenceMissing:
      "El día de referencia no está disponible porque el historial tiene una discontinuidad real el 31/12/2015. Esto también afecta al 01/01/2016.",
    runForecast: "Generar pronóstico",
    calculating: "Calculando...",
    latestResult: "Último resultado",
    storedPredictions: "Predicciones almacenadas",
    forecastLedger: "Libro de pronósticos",
    noStoredPredictions: "Todavía no hay predicciones almacenadas.",
    predictionVsActual: "Predicción vs Real",
    historicalComparison: "Comparación histórica",
    date: "Fecha",
    predicted: "Predicha",
    actual: "Real",
    absError: "Error abs.",
    matchWithActual: "Coincidencia con el valor real",
    model: "Modelo",
    notAvailable: "No disponible",
    historicalDemand: "Demanda histórica",
    recentDailyObservations: "Observaciones diarias recientes",
    noDemandRecords: "No hay registros de demanda.",
    selectorTooltip:
      "Fecha objetivo para el pronóstico H+1. Debe estar dentro del rango disponible y el día anterior debe existir en el historial.",
    predictionsTooltip:
      "Predicciones generadas por la API y almacenadas en PostgreSQL/Supabase para el modelo y fechas históricas seleccionadas.",
    activeModelTooltip:
      "Modelo desarrollado y evaluado en este proyecto para realizar pronósticos H+1 de demanda energética. La versión activa corresponde al modelo seleccionado tras comparar alternativas mediante evaluación temporal sobre datos históricos.",
    comparisonTooltip:
      "Demanda prevista, demanda real, error absoluto y relativo para los registros de predicción almacenados.",
    historicalTooltip:
      "Demanda diaria histórica que sirve como base de referencia para el pronóstico H+1 y la comparación del modelo.",
    backendUnavailable: "Backend no disponible",
    predictionUnavailable: "Pronóstico no disponible",
    recordCount: "registros almacenados",
    recordLabel: "registros",
    languageToggle: "Idioma",
    dataSource: "Fuente de datos: XM Colombia — información histórica de demanda energética del Sistema Interconectado Nacional (SIN).",
  },
} as const;

function getInitialLanguage(): Language {
  if (typeof window === "undefined") return "es";
  const stored = window.localStorage.getItem("spde-language");
  if (stored === "es" || stored === "en") return stored;
  return "es";
}

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });
  const payload = (await response.json()) as T & { detail?: string };
  if (!response.ok) throw new Error(payload.detail ?? `Request failed (${response.status})`);
  return payload;
}

function formatDateLabel(dateValue: string, lang: Language): string {
  const date = new Date(`${dateValue}T00:00:00`);
  if (Number.isNaN(date.getTime())) return dateValue;
  return new Intl.DateTimeFormat(lang === "es" ? "es-ES" : "en-GB", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(date);
}

function formatKwh(value: number | null): string {
  return value === null ? "Not available" : `${new Intl.NumberFormat("en-US").format(value)} kWh`;
}

function formatPercent(value: number | null): string {
  if (value === null || Number.isNaN(value)) return "Not available";
  return `${value.toFixed(2)}%`;
}

function getAbsoluteError(actual: number | null, predicted: number): number | null {
  return actual === null ? null : Math.abs(predicted - actual);
}

function getRelativeError(actual: number | null, predicted: number): number | null {
  if (actual === null || actual === 0) return null;
  return (Math.abs(predicted - actual) / Math.abs(actual)) * 100;
}

function getMatchWithActual(actual: number | null, predicted: number): number | null {
  const relativeError = getRelativeError(actual, predicted);
  if (relativeError === null) return null;
  return 100 - relativeError;
}

function getDateValidationMessage(value: string, lang: Language): string {
  if (!value) return "";
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) {
    return lang === "es" ? translations.es.invalidDate : translations.en.invalidDate;
  }
  const minDate = new Date(`${DATE_RANGE.min}T00:00:00`);
  const maxDate = new Date(`${DATE_RANGE.max}T00:00:00`);
  if (date < minDate) {
    return lang === "es" ? translations.es.dateBeforeStart : translations.en.dateBeforeStart;
  }
  if (date > maxDate) {
    return lang === "es" ? translations.es.dateAfterEnd : translations.en.dateAfterEnd;
  }
  const referenceDate = new Date(date);
  referenceDate.setDate(referenceDate.getDate() - 1);
  if (referenceDate.toISOString().slice(0, 10) === DATE_RANGE.discontinuity) {
    return lang === "es" ? translations.es.referenceMissing : translations.en.referenceMissing;
  }
  return "";
}

function App() {
  const [lang, setLang] = useState<Language>(getInitialLanguage);
  const [health, setHealth] = useState<"checking" | "online" | "offline">("checking");
  const [model, setModel] = useState<ActiveModel | null>(null);
  const [predictions, setPredictions] = useState<Prediction[]>([]);
  const [demand, setDemand] = useState<Demand[]>([]);
  const [targetDate, setTargetDate] = useState("2023-01-03");
  const [latestPrediction, setLatestPrediction] = useState<Prediction | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const t = (key: keyof typeof translations.en) => translations[lang][key];
  const dateIssue = getDateValidationMessage(targetDate, lang);
  const availableRangeText = `${t("availableFrom")} ${formatDateLabel(DATE_RANGE.min, lang)} ${t("to")} ${formatDateLabel(DATE_RANGE.max, lang)}`;

  useEffect(() => {
    window.localStorage.setItem("spde-language", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  async function refresh() {
    setError("");
    try {
      const [healthResponse, modelResponse, predictionResponse, demandResponse] = await Promise.all([
        request<{ status: "ok" }>("/health"),
        request<ActiveModel>("/api/v1/models/active"),
        request<ListResponse<Prediction>>("/api/v1/predictions?page=1&page_size=30"),
        request<ListResponse<Demand>>("/api/v1/demand?page=1&page_size=30"),
      ]);
      setHealth(healthResponse.status === "ok" ? "online" : "offline");
      setModel(modelResponse);
      setPredictions(predictionResponse.items);
      setDemand(demandResponse.items);
    } catch (reason) {
      setHealth("offline");
      setError(reason instanceof Error ? reason.message : t("backendUnavailable"));
    }
  }

  useEffect(() => {
    void refresh();
  }, []);

  async function createPrediction() {
    if (dateIssue) {
      setError(dateIssue);
      return;
    }
    setLoading(true);
    setError("");
    try {
      const prediction = await request<Prediction>("/api/v1/predictions", {
        method: "POST",
        body: JSON.stringify({ target_date: targetDate }),
      });
      setLatestPrediction(prediction);
      await refresh();
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : t("predictionUnavailable"));
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="shell">
      <header className="topbar">
        <div>
          <p className="kicker">SPDE / LIVE CONSOLE</p>
          <h1>Demand signal</h1>
        </div>
        <div className="topbar-right">
          <div className="language-switch" aria-label={t("languageLabel")}>
            <button type="button" className={lang === "en" ? "selected" : ""} onClick={() => setLang("en")}>EN</button>
            <span className="language-divider">|</span>
            <button type="button" className={lang === "es" ? "selected" : ""} onClick={() => setLang("es")}>ES</button>
          </div>
          <div className={`status status-${health}`}>
            <span className="status-dot" />
            {health === "checking" ? t("statusChecking") : health === "online" ? t("statusOnline") : t("statusOffline")}
          </div>
        </div>
      </header>

      {error && <div className="alert" role="alert">{error}</div>}

      <section className="hero-grid">
        <div className="hero-copy">
          <p className="eyebrow">{t("heroEyebrow")}</p>
          <h2>{t("heroTitle")}</h2>
          <p className="lede">{t("heroLead")}</p>
        </div>
        <div className="model-panel">
          <div className="panel-header">
            <span className="panel-label">{t("activeModel")}</span>
            <span className="info-badge" tabIndex={0} data-tooltip={t("activeModelTooltip")} aria-label={t("activeModelTooltip")}>?</span>
          </div>
          {model ? (
            <>
              <strong>{model.name}</strong>
              <div className="model-meta">
                <span>v{model.version}</span>
                <span>H+{model.horizon}</span>
              </div>
            </>
          ) : (
            <strong>{t("unavailable")}</strong>
          )}
        </div>
      </section>

      <section className="workspace-grid">
        <div className="forecast-card">
          <div className="card-heading">
            <div className="label-stack">
              <span className="panel-label">{t("newPrediction")}</span>
              <h3>{t("chooseDate")}</h3>
            </div>
            <span className="date-badge">{t("hPlusOne")}</span>
          </div>

          <div className="selector-field">
            <div className="field-header">
              <label htmlFor="target-date">{t("targetDate")}</label>
              <span className="info-badge" tabIndex={0} data-tooltip={t("selectorTooltip")} aria-label={t("selectorTooltip")}>?</span>
            </div>
            <div className="range-row">{availableRangeText}</div>
            <div className="date-control">
              <input
                id="target-date"
                type="date"
                min={DATE_RANGE.min}
                max={DATE_RANGE.max}
                value={targetDate}
                onChange={(event) => setTargetDate(event.target.value)}
                aria-invalid={Boolean(dateIssue)}
              />
            </div>
            <div className={`field-feedback ${dateIssue ? "error" : "ok"}`} role={dateIssue ? "alert" : "status"} aria-live="polite">
              {dateIssue || t("selectorReady")}
            </div>
          </div>

          <div className="forecast-form">
            <button type="button" onClick={() => void createPrediction()} disabled={loading || !targetDate || Boolean(dateIssue)}>
              {loading ? t("calculating") : t("runForecast")}
            </button>
          </div>

          {latestPrediction && (
            <div className="result">
              <span className="panel-label">{t("latestResult")}</span>
              <strong>{formatKwh(latestPrediction.predicted_demand_kwh)}</strong>
              <p>
                {latestPrediction.target_date} · {latestPrediction.model_version ?? model?.version ?? t("model")}
              </p>
            </div>
          )}
        </div>

        <div className="history-card">
          <div className="card-heading">
            <div className="label-stack">
              <span className="panel-label">{t("storedPredictions")}</span>
              <h3>{t("forecastLedger")}</h3>
            </div>
            <div className="count-wrap">
              <span className="info-badge small" tabIndex={0} data-tooltip={t("predictionsTooltip")} aria-label={t("predictionsTooltip")}>?</span>
              <span className="count">{predictions.length}</span>
            </div>
          </div>
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>{t("date")}</th>
                  <th>{t("predicted")}</th>
                  <th>{t("actual")}</th>
                </tr>
              </thead>
              <tbody>
                {predictions.slice(0, 8).map((item) => (
                  <tr key={item.id}>
                    <td>{item.target_date}</td>
                    <td>{formatKwh(item.predicted_demand_kwh)}</td>
                    <td>{formatKwh(item.actual_demand_kwh)}</td>
                  </tr>
                ))}
                {!predictions.length && (
                  <tr>
                    <td colSpan={3} className="empty">{t("noStoredPredictions")}</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      <section className="comparison-section">
        <div className="section-heading">
          <div className="label-stack">
            <span className="panel-label">{t("predictionVsActual")}</span>
            <h3>{t("historicalComparison")}</h3>
          </div>
          <div className="count-wrap">
            <span className="info-badge small" tabIndex={0} data-tooltip={t("comparisonTooltip")} aria-label={t("comparisonTooltip")}>?</span>
            <span className="muted">{predictions.length} {t("recordCount")}</span>
          </div>
        </div>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>{t("date")}</th>
                <th>{t("predicted")}</th>
                <th>{t("actual")}</th>
                <th>{t("absError")}</th>
                <th>{t("matchWithActual")}</th>
                <th>{t("model")}</th>
              </tr>
            </thead>
            <tbody>
              {predictions.slice(0, 8).map((item) => {
                const absError = getAbsoluteError(item.actual_demand_kwh, item.predicted_demand_kwh);
                const matchWithActual = getMatchWithActual(item.actual_demand_kwh, item.predicted_demand_kwh);
                const modelVersion = model && item.model_id === model.id ? `v${model.version}` : `model ${item.model_id.slice(0, 8)}`;
                return (
                  <tr key={item.id}>
                    <td>{item.target_date}</td>
                    <td>{formatKwh(item.predicted_demand_kwh)}</td>
                    <td>{formatKwh(item.actual_demand_kwh)}</td>
                    <td>{absError === null ? t("notAvailable") : formatKwh(absError)}</td>
                    <td className="match-cell">{matchWithActual === null ? t("notAvailable") : formatPercent(matchWithActual)}</td>
                    <td>{modelVersion}</td>
                  </tr>
                );
              })}
              {!predictions.length && (
                <tr>
                  <td colSpan={6} className="empty">{t("noStoredPredictions")}</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </section>

      <section className="demand-section">
        <div className="section-heading">
          <div className="label-stack">
            <span className="panel-label">{t("historicalDemand")}</span>
            <h3>{t("recentDailyObservations")}</h3>
          </div>
          <div className="count-wrap">
            <span className="info-badge small" tabIndex={0} data-tooltip={t("historicalTooltip")} aria-label={t("historicalTooltip")}>?</span>
            <span className="muted">{demand.length} {t("recordLabel")}</span>
          </div>
        </div>
        <div className="demand-strip">
          {demand.slice(-10).map((item) => (
            <div className="demand-item" key={item.date}>
              <span>{item.date}</span>
              <strong>{formatKwh(item.demand_kwh)}</strong>
            </div>
          ))}
          {!demand.length && <div className="empty-cell">{t("noDemandRecords")}</div>}
        </div>
      </section>

      <footer className="data-source-footer">
        <a
          href="https://www.xm.com.co/consumo/informes-demanda"
          target="_blank"
          rel="noreferrer"
          aria-label={t("dataSource")}
        >
          {t("dataSource")}
        </a>
      </footer>
    </main>
  );
}

createRoot(document.getElementById("root")!).render(<App />);